name: rastro_genetico2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  floor: ^1.4.2
  shared_preferences: ^2.2.1
  window_manager: ^0.3.6
  get: ^4.5.1
  splash_view: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2



flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/images/